### ISSUE TITLE
TypeError: 'unicode' does not have the buffer interface

### ISSUE THREAD

**Issue by nightsh** [rootio/rootio_web#114]
```
ERROR:waitress:Exception when serving /
Traceback (most recent call last):
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask_login.py", line 299, in _load_user
    return self._load_from_cookie(request.cookies[cookie_name])
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask_login.py", line 334, in _load_from_cookie
    user_id = decode_cookie(cookie)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask_login.py", line 468, in decode_cookie
    if safe_str_cmp(_cookie_digest(payload), digest):
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/werkzeug/security.py", line 117, in safe_str_cmp
    return _builtin_safe_str_cmp(a, b)
TypeError: 'unicode' does not have the buffer interface
ERROR:waitress:Exception when serving /favicon.ico
Traceback (most recent call last):
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1473, in full_dispatch_request
    rv = self.preprocess_request()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1666, in preprocess_request
    rv = func()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask_login.py", line 299, in _load_user
    return self._load_from_cookie(request.cookies[cookie_name])
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask_login.py", line 334, in _load_from_cookie
    user_id = decode_cookie(cookie)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask_login.py", line 468, in decode_cookie
    if safe_str_cmp(_cookie_digest(payload), digest):
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/werkzeug/security.py", line 117, in safe_str_cmp
    return _builtin_safe_str_cmp(a, b)
TypeError: 'unicode' does not have the buffer interface
```

**Comment by nightsh** [comment]
Update: it looks like it's related to cookies. Clearing cache / cookies in browser seems to "fix" the issue.
