### ISSUE TITLE
Error 500 on radio index

### ISSUE THREAD

**Issue by nightsh** [rootio/rootio_web#189]
Excerpt from the logs, it doesn't happen for all users:

```
[Wed Jan 23 15:46:21.939663 2019] [wsgi:error] [pid 23054:tid 139649688033024] [client 193.70.15.33:35262] TypeError: unsupported operand type(s) for *: 'NoneType' and 'int', referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.558297 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270] mod_wsgi (pid=23606): Exception occurred processing WSGI script '/opt/rootio/rootio_web/rootio.wsgi'., referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.562586 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270] Traceback (most recent call last):, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.563658 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.590617 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     return self.wsgi_app(environ, start_response), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.592575 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.593040 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     response = self.make_response(self.handle_exception(e)), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.593140 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.593495 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     reraise(exc_type, exc_value, tb), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.593613 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.593822 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     response = self.full_dispatch_request(), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594040 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594162 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     rv = self.handle_user_exception(e), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594291 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594366 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     reraise(exc_type, exc_value, tb), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594425 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594493 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     rv = self.dispatch_request(), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594554 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594624 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     return self.view_functions[rule.endpoint](**req.view_args), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594685 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/rootio_web/rootio/radio/views.py", line 33, in index, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594754 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     return render_template('radio/index.html', networks=networks, userid=current_user.id, now=datetime.now), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594815 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594897 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     context, ctx.app), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.594954 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/flask/templating.py", line 110, in _render, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595019 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     rv = template.render(context), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595074 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595141 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     return self.environment.handle_exception(exc_info, True), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595209 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/venvs/rootio_web/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595335 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     reraise(exc_type, exc_value, tb), referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595411 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/rootio_web/rootio/templates/radio/index.html", line 1, in top-level template code, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595501 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     {% extends "radio/layout.html" %}, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595582 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/rootio_web/rootio/templates/radio/layout.html", line 7, in top-level template code, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595656 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     {% set tabs = [, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595716 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/rootio_web/rootio/templates/layouts/base.html", line 120, in top-level template code, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595811 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     {% block container %}, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595873 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/rootio_web/rootio/templates/layouts/base.html", line 140, in block "container", referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.595972 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     {% block body %}, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.597076 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/rootio_web/rootio/templates/radio/index.html", line 82, in block "body", referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.604348 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     {% include 'radio/_analytics.html' %}, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.604465 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]   File "/opt/rootio/rootio_web/rootio/templates/radio/_analytics.html", line 32, in top-level template code, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.607114 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270]     {% if last_ping_interval > (station.analytic_update_frequency * 2) %}, referer: https://rootio.eu/user/
[Wed Jan 23 15:46:22.607942 2019] [wsgi:error] [pid 23606:tid 139649469060864] [client 193.70.15.33:35270] TypeError: unsupported operand type(s) for *: 'NoneType' and 'int', referer: https://rootio.eu/user/

```

**Comment by nightsh** [comment]
Closing as duplicate of #191.
