### ISSUE TITLE
Adding a station returns 500, but creates the station

### ISSUE THREAD

**Issue by nightsh** [rootio/rootio_web#99]
```
ERROR:waitress:Exception when serving /content/playlist/add/
Traceback (most recent call last):
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask_login.py", line 663, in decorated_view
    return func(*args, **kwargs)
  File "/opt/rootio/rootio_web/rootio/content/views.py", line 778, in content_musicplaylist_add
    return render_template('content/content_playlist.html', content_musicplaylist=content_musicplaylist, form=form)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/rootio/rootio_web/rootio/templates/content/content_playlist.html", line 3, in top-level template code
    {% extends "content/layout.html" %}
  File "/opt/rootio/rootio_web/rootio/templates/content/layout.html", line 7, in top-level template code
    {% set tabs = [
  File "/opt/rootio/rootio_web/rootio/templates/layouts/base.html", line 119, in top-level template code
    {% block container %}
  File "/opt/rootio/rootio_web/rootio/templates/layouts/base.html", line 139, in block "container"
    {% block body %}
  File "/opt/rootio/rootio_web/rootio/templates/content/content_playlist.html", line 9, in block "body"
    {{ render_form(url_for('content.content_musicplaylist', content_musicplaylist_id=content_musicplaylist.id), form) }}
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/helpers.py", line 312, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/app.py", line 1641, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/flask/helpers.py", line 305, in url_for
    force_external=external)
  File "/opt/rootio/venvs/rootio_web/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1620, in build
    raise BuildError(endpoint, values, method)
BuildError: ('content.content_musicplaylist', {'content_musicplaylist_id': 5}, None)
```

**Comment by judelove** [comment]
same for when you create a station
